#!/bin/bash
# setup/dev/nginx_service.sh — Nginx static file server for built dist/ on a VPS
#
# Sets up SERVICE mode: nginx serves the pre-built dist/ directories directly.
# No Vite dev servers needed — nginx reads files from disk.
#
# Domain pattern:  {project}.{parent}
#   Landing:       {project}.{parent}        → landing/dist/
#   Client portal: portal.{project}.{parent} → client-portal/dist/
#   Admin portal:  admin.{project}.{parent}  → admin-portal/dist/
#   Supabase API:  api.{project}.{parent}    → :54321 (proxied)
#
# State saved to:  setup/dev/.localdev-config
# Nginx config:    /etc/nginx/sites-available/{PROJECT}-service
#
# Does NOT touch the dev-proxy nginx config ({PROJECT}-dev).
# Run setup-nginx-localdev separately for that.
#
# Idempotent — safe to re-run. Loads previous values as defaults.
set -euo pipefail
SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT_DIR="$(cd "$SETUP_DIR/.." && pwd)"
source "$SETUP_DIR/lib/ui.sh"

CONFIG_FILE="$SETUP_DIR/dev/.localdev-config"
PROJECT=$(grep '^name:' "$ROOT_DIR/project.yaml" | awk '{print $2}')
NGINX_CONF="/etc/nginx/sites-available/${PROJECT}-service"
NGINX_LINK="/etc/nginx/sites-enabled/${PROJECT}-service"
OLD_NGINX_CONF="/etc/nginx/sites-available/${PROJECT}"
OLD_NGINX_LINK="/etc/nginx/sites-enabled/${PROJECT}"

header "NGINX SERVICE"
info "Mode: static file serving (nginx → built dist/ directories)"
info "Nginx config: ${NGINX_CONF}"
echo ""

# ── Load saved state ──────────────────────────────────────────────────────────
load_state() {
  local key=$1 default=${2:-}
  grep "^${key}=" "$CONFIG_FILE" 2>/dev/null | cut -d= -f2- || echo "$default"
}

SAVED_PARENT=$(load_state PARENT_DOMAIN)
SAVED_IP=$(load_state IP)
SAVED_EMAIL=$(load_state HTTPS_EMAIL)
SAVED_HTTPS=$(load_state HTTPS "no")

# ── Domain / IP ───────────────────────────────────────────────────────────────
DETECTED_IP=$(curl -4 -s --max-time 3 https://ifconfig.me 2>/dev/null || \
              ip addr show tailscale0 2>/dev/null | grep "inet " | awk '{print $2}' | cut -d/ -f1 || \
              hostname -I | awk '{print $1}')

info "Domain options:"
arrow "Parent domain  e.g. myapp.com  → ${PROJECT}.[input]"
arrow "               portals: portal.${PROJECT}.[input]  admin.${PROJECT}.[input]"
arrow "nip.io (auto)  ${DETECTED_IP}.nip.io — HTTP only"
echo ""
printf "  Parent domain ${DIM}[${SAVED_PARENT:-leave blank for nip.io}]${RESET}: "
read -r INPUT_DOMAIN
PARENT_DOMAIN="${INPUT_DOMAIN:-$SAVED_PARENT}"

if [ -n "$PARENT_DOMAIN" ]; then
  BASE_DOMAIN="${PROJECT}.${PARENT_DOMAIN}"
  IP="$DETECTED_IP"
  HTTPS_CAPABLE=true
else
  printf "  IP address ${DIM}[${SAVED_IP:-$DETECTED_IP}]${RESET}: "
  read -r INPUT_IP
  IP="${INPUT_IP:-${SAVED_IP:-$DETECTED_IP}}"
  BASE_DOMAIN="${PROJECT}.${IP}.nip.io"
  info "Using nip.io: ${BASE_DOMAIN} (HTTP only)"
  HTTPS_CAPABLE=false
fi

URL_LANDING="http://${BASE_DOMAIN}"
URL_PORTAL="http://portal.${BASE_DOMAIN}"
URL_ADMIN="http://admin.${BASE_DOMAIN}"
URL_API="http://api.${BASE_DOMAIN}"

echo ""
printf "  ${BOLD}Service URLs:${RESET}\n"
printf "    Landing:       ${URL_LANDING}\n"
printf "    Client portal: ${URL_PORTAL}\n"
printf "    Admin portal:  ${URL_ADMIN}\n"
printf "    Supabase API:  ${URL_API}\n"
echo ""

# ── Dist check ────────────────────────────────────────────────────────────────
for dir in landing client-portal admin-portal; do
  if [ ! -d "$ROOT_DIR/$dir/dist" ]; then
    warn "$dir/dist/ not found — run 'just build' before deploying."
  else
    success "$dir/dist/ found"
  fi
done
echo ""

# ── Exposure warning ──────────────────────────────────────────────────────────
warn "INTERNET EXPOSURE"
info "Built apps + Supabase API will be reachable from the network."
echo ""

if ! confirm "Continue?"; then info "Aborted."; exit 0; fi
echo ""

# ── Generate Nginx config ─────────────────────────────────────────────────────
NGINX_CONF_TMP=$(mktemp)

cat > "$NGINX_CONF_TMP" <<NGINX
# Nginx service mode — generated by setup/dev/nginx_service.sh
# Re-run: just setup-service-localdev
# Mode: static file serving from dist/ directories
# Domain: ${BASE_DOMAIN}
# Do NOT edit manually — re-run the script instead.
# HTTPS managed by certbot — do not remove certbot comment blocks.

NGINX

write_static_block() {
  local subdomain=$1 distdir=$2
  local server_name
  [ "$subdomain" = "root" ] && server_name="${BASE_DOMAIN}" \
                             || server_name="${subdomain}.${BASE_DOMAIN}"
  cat >> "$NGINX_CONF_TMP" <<BLOCK
server {
    listen 80;
    server_name ${server_name};

    root ${ROOT_DIR}/${distdir}/dist;
    index index.html;

    location / {
        try_files \$uri \$uri/ /index.html;
    }
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)\$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}

BLOCK
}

write_static_block "root"   "landing"
write_static_block "portal" "client-portal"
write_static_block "admin"  "admin-portal"

cat >> "$NGINX_CONF_TMP" <<NGINX
server {
    listen 80;
    server_name api.${BASE_DOMAIN};
    location / {
        proxy_pass http://localhost:54321;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX

# ── Migrate old config name → {PROJECT}-service ───────────────────────────────
if [ -f "$OLD_NGINX_CONF" ] || [ -L "$OLD_NGINX_LINK" ]; then
  info "Migrating old nginx config (${PROJECT} → ${PROJECT}-service)..."
  sudo rm -f "$OLD_NGINX_LINK"
  sudo rm -f "$OLD_NGINX_CONF"
  success "Old config removed"
fi

info "Installing nginx config: ${NGINX_CONF}..."
sudo cp "$NGINX_CONF_TMP" "$NGINX_CONF"
rm -f "$NGINX_CONF_TMP"
[ -L "$NGINX_LINK" ] || sudo ln -s "$NGINX_CONF" "$NGINX_LINK"
sudo nginx -t && sudo nginx -s reload && success "Nginx reloaded (static service)"

# ── HTTPS via Let's Encrypt ───────────────────────────────────────────────────
echo ""
info "HTTPS setup (Let's Encrypt)"

WANT_HTTPS=false
if ! $HTTPS_CAPABLE; then
  info "Skipping HTTPS — nip.io hits Let's Encrypt rate limits."
  info "Use a custom domain for HTTPS."
else
  if ! command -v certbot > /dev/null 2>&1; then
    warn "certbot not installed."
    if confirm "Install certbot now?"; then
      sudo apt-get install -y certbot python3-certbot-nginx && success "certbot installed"
    fi
  fi

  if command -v certbot > /dev/null 2>&1; then
    CERT_PATH="/etc/letsencrypt/live/${BASE_DOMAIN}"
    if [ -f "${CERT_PATH}/cert.pem" ] && \
       [ "$(( ( $(date -d "$(openssl x509 -enddate -noout -in "${CERT_PATH}/cert.pem" | cut -d= -f2)" +%s 2>/dev/null || echo 0) - $(date +%s) ) / 86400 ))" -gt 0 ] 2>/dev/null; then
      info "Valid cert found — re-applying..."
      WANT_HTTPS=true
    else
      if confirm "Set up HTTPS with Let's Encrypt? (requires port 80 publicly reachable)"; then
        WANT_HTTPS=true
      fi
    fi
  fi
fi

if $WANT_HTTPS; then
  EMAIL="${SAVED_EMAIL:-}"
  if [ -z "$EMAIL" ]; then
    printf "  Email for Let's Encrypt notifications: "
    read -r EMAIL
  fi

  if [ -z "$EMAIL" ]; then
    fail "Email required for Let's Encrypt."; WANT_HTTPS=false
  else
    ALL_DOMAINS="${BASE_DOMAIN},portal.${BASE_DOMAIN},admin.${BASE_DOMAIN},api.${BASE_DOMAIN}"
    info "Running certbot for: $ALL_DOMAINS"
    if sudo certbot --nginx \
        --non-interactive --agree-tos --keep-until-expiring --redirect \
        --email "$EMAIL" --domains "$ALL_DOMAINS" 2>&1; then
      success "HTTPS enabled"
      URL_LANDING="https://${BASE_DOMAIN}"
      URL_PORTAL="https://portal.${BASE_DOMAIN}"
      URL_ADMIN="https://admin.${BASE_DOMAIN}"
      URL_API="https://api.${BASE_DOMAIN}"
      SAVED_HTTPS="yes"
      SAVED_EMAIL="$EMAIL"
    else
      warn "certbot failed. Staying on HTTP."
      WANT_HTTPS=false
    fi
  fi
fi

[ "$WANT_HTTPS" = "false" ] && SAVED_HTTPS="no"

# ── Update .env.local with service URLs ───────────────────────────────────────
info "Updating .env.local with service URLs..."
set_env_force() {
  local key=$1 value=$2 file="$ROOT_DIR/.env.local"
  [ -f "$file" ] || cp "$ROOT_DIR/.env.local.example" "$file"
  sed -i "/^${key}=/d" "$file"
  echo "${key}=${value}" >> "$file"
  success "$key → $value"
}
set_env_force "SITE_URL"          "$URL_PORTAL"
set_env_force "VITE_APP_URL"      "$URL_PORTAL"
set_env_force "VITE_SUPABASE_URL" "$URL_API"
set_env_force "VITE_API_URL"      "${URL_API}/functions/v1"

# ── Save state ────────────────────────────────────────────────────────────────
mkdir -p "$(dirname "$CONFIG_FILE")"
# Preserve SERVICE_NAME if already set
EXISTING_SERVICE=$(load_state SERVICE_NAME "${PROJECT}-dev")
cat > "$CONFIG_FILE" <<STATE
IP=${IP}
PARENT_DOMAIN=${PARENT_DOMAIN:-}
BASE_DOMAIN=${BASE_DOMAIN}
HTTPS=${SAVED_HTTPS}
HTTPS_EMAIL=${SAVED_EMAIL:-}
URL_LANDING=${URL_LANDING}
URL_PORTAL=${URL_PORTAL}
URL_ADMIN=${URL_ADMIN}
URL_API=${URL_API}
SERVICE_NAME=${EXISTING_SERVICE}
STATE
success "State saved → setup/dev/.localdev-config"

# ── Print URL table ───────────────────────────────────────────────────────────
W1=14
W2=$(( ${#URL_PORTAL} + 2 ))
[ $W2 -lt 44 ] && W2=44
SEP1=$(printf '─%.0s' $(seq 1 $((W1 + 2))))
SEP2=$(printf '─%.0s' $(seq 1 $((W2 + 1))))

echo ""
printf "╭%s┬%s╮\n" "$SEP1" "$SEP2"
printf "│ %-${W1}s │ %-${W2}s│\n" "Landing"       "$URL_LANDING"
printf "│ %-${W1}s │ %-${W2}s│\n" "Client portal" "$URL_PORTAL"
printf "│ %-${W1}s │ %-${W2}s│\n" "Admin portal"  "$URL_ADMIN"
printf "│ %-${W1}s │ %-${W2}s│\n" "Supabase API"  "$URL_API"
printf "╰%s┴%s╯\n" "$SEP1" "$SEP2"
echo ""
info "Build and deploy:"
arrow "just deploy-local-service"
printf "  ${DIM}Studio (SSH tunnel): ssh -L 54323:localhost:54323 <vps> → http://localhost:54323${RESET}\n"
