#!/bin/bash
# setup/branding/apply-branding.sh
# Propagates branding/ → all targets (CSS vars, manifests, app.json, logos)
set -euo pipefail
SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT_DIR="$(cd "$SETUP_DIR/.." && pwd)"
source "$SETUP_DIR/lib/ui.sh"
source "$SETUP_DIR/lib/yaml.sh"

BRANDING_DIR="$ROOT_DIR/branding"
PALETTE_FILE="$BRANDING_DIR/palette.js"

header "APPLY BRANDING"

if [ ! -f "$PALETTE_FILE" ]; then
  fail "branding/palette.js not found. Run: just setup branding"
  exit 1
fi

# Read palette values from palette.js (JS object → parse with node)
read_palette() {
  node -e "const p = require('$PALETTE_FILE'); console.log(p.$1 || '');" 2>/dev/null || echo ""
}

PRIMARY=$(read_palette "primary")
SECONDARY=$(read_palette "secondary")
ACCENT=$(read_palette "accent")
SUCCESS_COLOR=$(read_palette "success")
DANGER=$(read_palette "danger")
APP_NAME=$(read_yaml "display_name")
APP_NAME=${APP_NAME:-"App"}

[ -z "$PRIMARY" ] && { fail "palette.js missing 'primary'. Regenerate: just setup branding"; exit 1; }

info "Primary:   $PRIMARY"
info "Secondary: $SECONDARY"
info "Accent:    $ACCENT"
echo ""

# ── Update commons/styles/globals.css ──────────────────────────────────────
CSS_FILE="$ROOT_DIR/commons/styles/globals.css"
if [ -f "$CSS_FILE" ]; then
  sed -i \
    -e "s|--color-primary: .*;|--color-primary: $PRIMARY;|" \
    -e "s|--color-secondary: .*;|--color-secondary: $SECONDARY;|" \
    -e "s|--color-accent: .*;|--color-accent: $ACCENT;|" \
    -e "s|--color-success: .*;|--color-success: $SUCCESS_COLOR;|" \
    -e "s|--color-danger: .*;|--color-danger: $DANGER;|" \
    "$CSS_FILE"
  success "commons/styles/globals.css updated"
fi

# ── Copy logos ──────────────────────────────────────────────────────────────
for logo in logo-large.svg logo-small.svg logo-favicon.svg; do
  for dir in client-portal/public admin-portal/public landing/public; do
    if [ -f "$BRANDING_DIR/$logo" ] && [ -d "$ROOT_DIR/$dir" ]; then
      cp "$BRANDING_DIR/$logo" "$ROOT_DIR/$dir/$logo"
    fi
  done
done
success "Logos copied to portal public/ dirs"

# ── Inline logo-mark in landing/index.html ──────────────────────────────────
LANDING_HTML="$ROOT_DIR/landing/index.html"
LOGO_MARK="$BRANDING_DIR/logo-small.svg"
if [ -f "$LANDING_HTML" ] && [ -f "$LOGO_MARK" ]; then
  SVG_CONTENT=$(cat "$LOGO_MARK")
  python3 - <<PYEOF
import re, sys
html = open('$LANDING_HTML').read()
inner = open('$LOGO_MARK').read().strip()
# Wrap with size attrs matching nav usage, preserve markers
replacement = '<!-- LOGO-MARK-START -->\n      ' + \
  re.sub(r'^<svg', '<svg width="48" height="48"', inner, count=1) + \
  '\n      <!-- LOGO-MARK-END -->'
html = re.sub(
  r'<!-- LOGO-MARK-START -->.*?<!-- LOGO-MARK-END -->',
  replacement, html, flags=re.DOTALL)
open('$LANDING_HTML', 'w').write(html)
PYEOF
  success "landing/index.html inline logo-mark updated"
fi

# ── Update client-portal/public/manifest.json ──────────────────────────────
MANIFEST="$ROOT_DIR/client-portal/public/manifest.json"
if [ -f "$MANIFEST" ]; then
  node -e "
const fs = require('fs');
const m = JSON.parse(fs.readFileSync('$MANIFEST','utf8'));
m.name = '$APP_NAME';
m.short_name = '$APP_NAME';
m.theme_color = '$PRIMARY';
m.background_color = '$PRIMARY';
fs.writeFileSync('$MANIFEST', JSON.stringify(m, null, 2));
"
  success "client-portal/public/manifest.json updated"
fi

# ── Update mobile-app/app.json branding fields ─────────────────────────────
APP_JSON="$ROOT_DIR/mobile-app/app.json"
if [ -f "$APP_JSON" ]; then
  node -e "
const fs = require('fs');
const a = JSON.parse(fs.readFileSync('$APP_JSON','utf8'));
a.expo.name = '$APP_NAME';
a.expo.primaryColor = '$PRIMARY';
a.expo.splash = { ...a.expo.splash, backgroundColor: '$PRIMARY' };
if (a.expo.android) a.expo.android.navigationBarColor = '$PRIMARY';
fs.writeFileSync('$APP_JSON', JSON.stringify(a, null, 2));
"
  success "mobile-app/app.json branding fields updated"
fi

# ── Update branding/colors.yaml ────────────────────────────────────────────
cat > "$BRANDING_DIR/colors.yaml" <<EOF
# Branding colors — generated by apply-branding.sh
primary:   $PRIMARY
secondary: $SECONDARY
accent:    $ACCENT
success:   $SUCCESS_COLOR
danger:    $DANGER
EOF
success "branding/colors.yaml updated"

echo ""
success "Branding applied to all targets."
info "Rebuild to see changes: just build"
